/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    application
}

repositories {
   
    mavenCentral()
}
dependencies {
    implementation("ch.qos.logback:logback-classic:1.5.16")
    implementation("org.springframework:spring-context:6.2.2")
    implementation("org.springframework:spring-tx:6.2.2")

    implementation("org.springframework.data:spring-data-jpa:3.4.2")

    implementation("org.hibernate.orm:hibernate-core:6.6.5.Final")

    implementation("com.zaxxer:HikariCP:6.2.1")

    implementation("com.h2database:h2:2.3.232")

    implementation("jakarta.annotation:jakarta.annotation-api:3.0.0")

    implementation("org.aspectj:aspectjweaver:1.9.22.1")

    implementation(libs.guava)
}
testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.11.1")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "ru.bsuedu.cad.lab.App"
}
