CREATE TABLE CATEGORIES (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000)
);

CREATE TABLE PRODUCTS (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    CATEGORY_ID BIGINT NOT NULL,
    PRICE DOUBLE NOT NULL,
    STOCK_QUANTITY INT NOT NULL,
    IMAGE_URL VARCHAR(500),
    CREATED_AT DATE,
    UPDATED_AT DATE,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
);